"""002

Revision ID: 981d5cad8866
Revises: ec0a70b3f3ea
Create Date: 2023-04-20 19:46:28.521382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981d5cad8866'
down_revision = 'ec0a70b3f3ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipped_date', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('total_cost', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('order_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'total_cost')
    op.drop_column('orders', 'shipped_date')
    # ### end Alembic commands ###
